# default identity
idp.voltage-auto.voltage.storage.path={{voltageStoragePath}}
idp.voltage-auto.voltage.trust.store.path={{voltageTrustStorePath}}
idp.voltage-auto.voltage.enable={{voltageEnable}}
idp.voltage-auto.voltage.key.server.url={{voltageKeyServerUrl}}
idp.voltage-auto.voltage.mech.id=${global_voltage_mechid}
idp.voltage-auto.voltage.password=${global_voltage_password}
idp.voltage-auto.voltage.identity.cust.id={{voltageIdentityCustId}}
idp.voltage-auto.voltage.identity.cust.pci={{voltageIdentityCustPci}}
idp.voltage-auto.voltage.identity.emp.id={{voltageIdentityEmpId}}
idp.voltage-auto.voltage.exception.to.be.thrown=true


# by BSI identity
idp.voltage-auto.voltage.identity.bsi.enable={{voltageBsiEnable}}
idp.voltage-auto.voltage.identity.bsi.mech.id=${global_voltage_mechid}
idp.voltage-auto.voltage.identity.bsi.password=${global_voltage_password}
idp.voltage-auto.voltage.identity.bsi.cust.id={{voltageBsiIdentityCustId}}
idp.voltage-auto.voltage.identity.bsi.cust.pci={{voltageBsiIdentityCustPci}}
idp.voltage-auto.voltage.identity.bsi.emp.id={{voltageBsiIdentityEmpId}}


# by EXT3 identity
idp.voltage-auto.voltage.identity.ext3.enable={{voltageExtEnable}}
idp.voltage-auto.voltage.identity.ext3.mech.id=${global_voltage_mechid}
idp.voltage-auto.voltage.identity.ext3.password=${global_voltage_password}
idp.voltage-auto.voltage.identity.ext3.cust.id={{voltageExtIdentityCustId}}
idp.voltage-auto.voltage.identity.ext3.cust.pci={{voltageExtIdentityCustPci}}
idp.voltage-auto.voltage.identity.ext3.emp.id={{voltageExtIdentityEmpId}}