#Properties to enable custom MDC headers in baselogback.xml
#custom_mdc_header1=xxxxxx
#custom_mdc_header2=xxxxxx
#custom_mdc_header3=xxxxxx
#custom_mdc_header4=xxxxxx
#custom_mdc_header5=xxxxxx
#custom_mdc_header6=xxxxxx
#custom_mdc_header7=xxxxxx
#custom_mdc_header8=xxxxxx
#custom_mdc_header9=xxxxxx
#custom_mdc_header10=xxxxxx
