# If the environment property system_properties_path contains a path to a file  , System properties created using the file. If the environment variable not present, system.properties in the class path is used for system property creation 

# Default parameters during application startup.
info.build.artifact= EPOCHOfferMs
info.build.name=com.att.idp
info.build.version=0.0.1-SNAPSHOT

# Spring configuration files
spring.config.location=opt/config/
spring.config.name=application

kubernetes.namespace=com-att-idp

# Configure the Logback config path
logging.config=opt/config/logback.xml

# AAF user roles config file
aaf.roles.properties=opt/config/AAFUserRoles.properties

# Configuration File (SecurityFilterExpressions.cfg) Path for the SecurityPatternLayout configured in the logback.xml
SecurityFilePath=opt/config/

# Config file entry for Hazelcast
#spring.hazelcast.config=file:opt/config/hazelcast-client.xml

#Config file entry for Redis

# t-APM kill switch. Enter values as comma separated. e.g. dev,test
# Valid values dev, test, stage, perf , prod
idp.t-apm.disabled=

org.owasp.esapi.resources=opt/config/
log.security.filter.config=opt/config/security-filter-config.yaml

server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain
server.compression.min-response-size=1024
