spring.application.name=commercetool

# ---- Staging1 (epoch-staging) ----
STAGING1_CLIENTID=lom_T-CZu3JA2N3osKYl4g74
STAGING1_CLIENTSECRET=QAn64M-63n4rlpFyt2YQZmNq4TYoyfn3
STAGING1_SCOPES=manage_orders:epoch-staging manage_customers:epoch-staging manage_products:epoch-staging manage_discount_codes:epoch-staging manage_customer_groups:epoch-staging manage_states:epoch-staging manage_categories:epoch-staging manage_types:epoch-staging

# ---- Staging2 (epoch-staging2) ----
STAGING2_APIURI=https://epochmw-development.directv.com/staging2
STAGING2_CLIENTID=Vxjd_1L0y8LaupK2qWejWPOG
STAGING2_CLIENTSECRET=ODvZFpP6Kx7QJv0-rtVomCScFrTaaNIw
STAGING2_SCOPES=manage_states:epoch-staging2 manage_products:epoch-staging2 manage_categories:epoch-staging2 manage_customer_groups:epoch-staging2 manage_customers:epoch-staging2 manage_types:epoch-staging2 manage_discount_codes:epoch-staging2 manage_cart_discounts:epoch-staging2 manage_orders:epoch-staging2

# ---- Dev (epoch-staging used as dev) ----
DEV_CLIENTID=iTk5kNMC-Uuz2LripDSrHn3V
DEV_CLIENTSECRET=pbYF6VBsbvHbvS1IzicNxJLS2YFw6ePi
DEV_SCOPES=manage_project:epoch-dev manage_api_clients:epoch-dev view_api_clients:epoch-dev

# ---- Staging3 (epoch-staging3) ----
STAGING3_CLIENTID=mKmmWi0MAeoHyxPrRumRqVOV
STAGING3_CLIENTSECRET=fbO5r2lD8lzsRqQYaEn9H17fSROea91M
STAGING3_SCOPES=manage_customers:epoch-staging3 manage_customer_groups:epoch-staging3 manage_discount_codes:epoch-staging3 manage_types:epoch-staging3 manage_standalone_prices:epoch-staging3 manage_categories:epoch-staging3 manage_products:epoch-staging3 manage_states:epoch-staging3 manage_cart_discounts:epoch-staging3 manage_orders:epoch-staging3 manage_key_value_documents:epoch-staging3

# ---- Production7 (epoch-production7) ----
PRODUCTION7_CLIENTID=zz2WFQKWXybylhyZxx7jtUNw
PRODUCTION7_CLIENTSECRET=SPMN3wRwLqGVjCdjBJmkO9eginikjn01
PRODUCTION7_SCOPES=manage_states:epoch-production7 manage_categories:epoch-production7 manage_orders:epoch-production7 manage_types:epoch-production7 manage_products:epoch-production7 manage_customer_groups:epoch-production7 manage_customers:epoch-production7

# ---- Production8 (epoch-production8) ----
PRODUCTION8_CLIENTID=a5HTd6TNhcepF4bHQSgoDUnQ
PRODUCTION8_CLIENTSECRET=EKTls4tmpw9ZD0hcHMxIYiBRFREz4OQu
PRODUCTION8_SCOPES=manage_orders:epoch-production8 manage_types:epoch-production8 manage_states:epoch-production8 manage_products:epoch-production8 manage_customers:epoch-production8 manage_customer_groups:epoch-production8 manage_categories:epoch-production8

server.port=8081
